### ISSUE TITLE
Pihole API Template for 6.0

### ISSUE THREAD

**Issue by ghost** [zabbix/community-templates#78]
When I import the template I get
`    Cannot add a non-numeric item "Reply IP" to graph "DNS replies".`

https://github.com/zabbix/community-templates/blob/main/Applications/template_pi-hole_api/6.0/template_pi-hole_api.yaml

**Comment by JulioQc** [comment]
I have the same issue with the error at template import:

```
Undefined index: templates [zabbix.php:22 → require_once() → ZBase->run() → ZBase->processRequest() → CController->run() → CControllerPopupImport->doAction() → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → CConfigurationImport->import() → CConfigurationImport->processTemplates() → CTemplateImporter->import() in include/classes/import/importers/CTemplateImporter.php:71]
 Cannot add a non-numeric item "Reply IP" to graph "DNS replies".
```

You can work around the issue by excluding graphs at template import. Or delete line 549 ("value_type: TEXT" for item 'Reply IP') in the YAML before import. It'll default to numeric unsigned which makes more sense for a graph. Not sure why it got set to TEXT to begin with... 

Running Zabbix 6.0.3

**Comment by nikoloskid** [comment]
Yes, I fixed it in a similar way and I also pushed a change, so hopefully it will be merged.

**Comment by nikoloskid** [comment]
#80

**Comment by stevefxp1** [comment]
The import issue still exists...I just downloaded the template and tried to upload it. Getting same error.
